#!/bin/bash

[[ -z $(which java) ]] && echo "Error: Java is not installed." >&2 && exit 1

JAR=$(dirname $0)/mf-import-check.jar

[[ ! -f ${JAR} ]] && echo "Error: ${JAR} is not found." >&2 && exit 2

java -cp ${JAR} vicnode.checker.cli.MFImportCheck ${1+"$@"}